export const FEATURE_STATUS = {
  READY: "ready",
  BETA: "beta",
  PARTIAL: "partial",
  PLANNED: "planned",
};

export const featureReadinessCatalog = {
  "/dashboard": {
    status: FEATURE_STATUS.READY,
    tier: 1,
    owner: "product",
    source: "iiko-cloud + iiko-olap",
    lastReviewedAt: "2026-04-18",
    knownLimitations: ["Часть KPI не имеет drill-down на всех срезах"],
  },
  "/revenue": {
    status: FEATURE_STATUS.READY,
    tier: 1,
    owner: "frontend",
    source: "iiko-olap",
    lastReviewedAt: "2026-04-18",
    knownLimitations: ["LFL-пояснения по методике не вынесены в интерфейс"],
  },
  "/delivery-sla": {
    status: FEATURE_STATUS.READY,
    tier: 1,
    owner: "backend",
    source: "iiko-cloud-deliveries",
    lastReviewedAt: "2026-04-18",
    knownLimitations: ["Требуется активный iikoCloud API, иначе отчет недоступен"],
  },
  "/stop-list": {
    status: FEATURE_STATUS.READY,
    tier: 1,
    owner: "operations",
    source: "iiko-stop-list",
    lastReviewedAt: "2026-04-18",
    knownLimitations: ["История статусов доступна частично"],
  },
  "/clients": {
    status: FEATURE_STATUS.READY,
    tier: 1,
    owner: "analytics",
    source: "iiko-cloud-deliveries",
    lastReviewedAt: "2026-04-18",
    knownLimitations: ["Профили клиентов имеют деградацию при лимитах API"],
  },
  "/marketing-sources": {
    status: FEATURE_STATUS.BETA,
    tier: 2,
    owner: "analytics",
    source: "iiko-cloud-deliveries",
    lastReviewedAt: "2026-04-18",
    knownLimitations: ["Требуется активный iikoCloud API, иначе отчет недоступен"],
  },
  "/top-dishes": {
    status: FEATURE_STATUS.BETA,
    tier: 2,
    owner: "analytics",
    source: "iiko-olap",
    lastReviewedAt: "2026-04-18",
    knownLimitations: ["Нет сравнения по LFL на уровне позиции"],
  },
  "/delivery-summary": {
    status: FEATURE_STATUS.BETA,
    tier: 2,
    owner: "operations",
    source: "iiko-cloud-deliveries",
    lastReviewedAt: "2026-04-18",
    knownLimitations: ["Требуется активный iikoCloud API, иначе отчет недоступен"],
  },
  "/delivery-delays": {
    status: FEATURE_STATUS.BETA,
    tier: 2,
    owner: "operations",
    source: "iiko-cloud-deliveries",
    lastReviewedAt: "2026-04-18",
    knownLimitations: ["Требуется активный iikoCloud API, иначе отчет недоступен"],
  },
  "/foodcost": {
    status: FEATURE_STATUS.BETA,
    tier: 2,
    owner: "finance",
    source: "iiko-olap",
    lastReviewedAt: "2026-04-18",
    knownLimitations: ["Пороги фудкоста не унифицированы по точкам"],
  },
  "/courier-map": {
    status: FEATURE_STATUS.PARTIAL,
    tier: 3,
    owner: "operations",
    source: "iiko-cloud-deliveries",
    lastReviewedAt: "2026-04-18",
    knownLimitations: ["Неполное покрытие заказов с координатами"],
  },
  "/promotions": {
    status: FEATURE_STATUS.PARTIAL,
    tier: 3,
    owner: "marketing",
    source: "iiko-olap",
    lastReviewedAt: "2026-04-18",
    knownLimitations: ["Нет детализации по промо-механикам"],
  },
  "/production-forecast": {
    status: FEATURE_STATUS.PARTIAL,
    tier: 3,
    owner: "operations",
    source: "aggregated",
    lastReviewedAt: "2026-04-18",
    knownLimitations: ["Прогноз пока без вероятностного коридора"],
  },
  "/plans": {
    status: FEATURE_STATUS.PARTIAL,
    tier: 3,
    owner: "finance",
    source: "manual + aggregated",
    lastReviewedAt: "2026-04-18",
    knownLimitations: ["Связка факт/план не покрывает все метрики"],
  },
  "/courier-kpi": {
    status: FEATURE_STATUS.BETA,
    tier: 2,
    owner: "operations",
    source: "iiko-cloud-deliveries",
    lastReviewedAt: "2026-04-18",
    knownLimitations: ["Требуется активный iikoCloud API, иначе отчет недоступен"],
  },
  "/hourly-sales": {
    status: FEATURE_STATUS.BETA,
    tier: 2,
    owner: "analytics",
    source: "iiko-olap",
    lastReviewedAt: "2026-04-18",
    knownLimitations: ["Нет сравнения час-к-часу по LFL"],
  },
  "/product-abc": {
    status: FEATURE_STATUS.BETA,
    tier: 2,
    owner: "analytics",
    source: "iiko-olap",
    lastReviewedAt: "2026-04-18",
    knownLimitations: ["Нужен split по подразделениям на уровне ABC"],
  },
  "/menu-assortment": {
    status: FEATURE_STATUS.BETA,
    tier: 2,
    owner: "analytics",
    source: "iiko-olap",
    lastReviewedAt: "2026-04-18",
    knownLimitations: ["Legacy alias. Используйте /product-abc"],
  },
};

export function getFeatureReadiness(routePath) {
  return (
    featureReadinessCatalog[routePath] || {
      status: FEATURE_STATUS.PLANNED,
      tier: 3,
      owner: "unassigned",
      source: "unknown",
      lastReviewedAt: null,
      knownLimitations: ["Статус не определен"],
    }
  );
}
